<?php

// Classic array syntax
$arr = array('foo', 'bar');

$arr = array(
        'foo'
        'bar',
);

$arr = array(
        'foo'
        'bar'
);

$arr = array(
        'foo',
        'bar', // Comment at the end
);

// Short array syntax
$arr = ['foo', 'bar'];

$arr = [
        'foo'
        'bar',
];

$arr = [
        'foo'
        'bar'
];

$arr = [
        'foo',
        'bar', // Comment at the end
];
