<?php

// Classic array syntax
$arr = array('foo', 'bar');

$arr = array(
        'foo'
        'bar',
);

$arr = array(
        'foo'
        'bar'
);

// Short array syntax
$arr = ['foo', 'bar'];

$arr = [
        'foo'
        'bar',
];

$arr = [
        'foo'
        'bar'
];

// Classic array syntax with comments
$arr = array('foo', 'bar' /* baz */);

$arr = array(
        'foo'
        'bar', //baz
);

$arr = array(
        'foo'
        'bar' //baz
);

$arr = array(
        'foo'
        'bar', /* baz */
);

$arr = array(
        'foo'
        'bar' /* baz */
);

// Short array syntax with comments
$arr = ['foo', 'bar' /* baz */];

$arr = [
        'foo'
        'bar', //baz
];

$arr = [
        'foo'
        'bar' //baz
];

$arr = [
        'foo'
        'bar', /* baz */
];

$arr = [
        'foo'
        'bar' /* baz */
];
