<?php

$a = $b++;

$a = ++$b;

$a = $b--;

$a = --$b;

$a = ++ $b;

$a = -- $b;

$a = $b ++;

$a = $b --;

$a->b++;

$a->b--;

++$a->b;

--$a->b;

$a->b ++;

$a->b --;

++ $a->b;

-- $a->b;

$a[0]++;

$a[0]--;

++$a[0];

--$a[0];

$a[0] ++;

$a[0] --;

++ $a[0];

-- $a[0];

++Class::$v;

--Class::$v;

Class::$v++;

Class::$v--;

++ Class::$v;

-- Class::$v;

Class::$v ++;

Class::$v --;

++self::$v;

--self::$v;

self::$v++;

self::$v--;

++ self::$v;

-- self::$v;

self::$v ++;

self::$v --;
