<?php

// classic array syntax
$arr = array('foo', 'bar');

$arr = array(
        'foo'
        'bar',
);

$arr = array(
        'foo'
        'bar'
);

$arr = array(
);

// short array syntax
$arr = ['foo', 'bar'];

$arr = [
        'foo'
        'bar',
];

$arr = [
        'foo'
        'bar'
];

$arr = [
];

// classic array syntax with comments
$arr = array('foo', 'bar' /* baz */);

$arr = array(
        'foo'
        'bar', //baz
);

$arr = array(
        'foo'
        'bar' //baz
);

$arr = array(
        'foo'
        'bar', /* baz */
);

$arr = array(
        'foo'
        'bar' /* baz */
);

$arr = array(
    //'foo' => 'bar'
);

$arr = array(
    //'foo' => 'bar',
);

// short array syntax with comments
$arr = ['foo', 'bar' /* baz */];

$arr = [
        'foo'
        'bar', //baz
];

$arr = [
        'foo'
        'bar' //baz
];

$arr = [
        'foo'
        'bar', /* baz */
];

$arr = [
        'foo'
        'bar' /* baz */
];

$arr = [
];

$arr = [
    //'foo' => 'bar'
];

$arr = [
    //'foo' => 'bar',
];
